# Generated by Django 4.2 on 2024-03-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_img',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRftcWMZycPdTp4H5yYhp9SroBMfuVYJLLPDIQ4JvLRpSSHhnwIwPKmeNXeBlKRY88p8C8&usqp=CAU', max_length=500),
        ),
    ]
